# Auto-generated by PhonAcq Assistant Wordlist Editor
# Save date: 2025-06-24 08:52:15

WORD_GROUPS = [
    {
        '你好': ('nǐ hǎo', ''),
        '世界': ('shì jiè', ''),
        '这是一个中文句子': ('', ''),
    },
    {
        'こんにちは': ('konnichiwa', ''),
        'ありがとうございます': ('arigatō gozaimasu', ''),
        'これは日本語の文章です': ('', ''),
    },
    {
        '안녕하세요': ('annyeonghaseyo', ''),
        '감사합니다': ('gamsahamnida', ''),
        '이것은 한국어 문장입니다': ('', ''),
    },
    {
        'Привет': ('Privet', ''),
        'Спасибо': ('Spasibo', ''),
        'Это предложение на русском языке': ('', ''),
    },
    {
        'Hello': ('həˈloʊ', ''),
        'Thank you': ('θæŋk juː', ''),
        'This is an English sentence.': ('', ''),
    },
    {
        '私の名前はSagerです': ('Watashi no namae wa Sager desu', ''),
        '東京タワーは高い': ('Tōkyō tawā wa takai', ''),
    },
    {
        '我喜欢Python': ('', ''),
        '这是一个test': ('', ''),
    },
    {
        'Мой favorite цвет – синий': ('', ''),
        'Давай сделаем test': ('', ''),
    },
    {
        'Sagerさんは中国人です': ('', ''),
    },
    {
        'Bonjour': ('bɔ̃ʒuʁ', 'fr-fr'),
        '你好': ('', 'en-uk'),
        'Привет': ('', 'ja'),
    },
]
